#!/usr/bin/env python3

import requests
import sys

url = 'https://www.cs.auckland.ac.nz/~pgut001/dumpasn1.cfg'
if len(sys.argv) > 1:
    url = sys.argv[1]
cfg = requests.get(url)

oids = {}
current = None

for l in cfg.iter_lines(decode_unicode=True):
    l = l.strip()
    if l.startswith('#') or not l:
        continue
    if '=' in l:
        attr, val = l.split('=', maxsplit=1)
        attr, val = attr.strip(), val.strip()
    else:
        attr, val = l, True
    if attr == 'OID':
        oid = '.'.join(val.split())
        current = oids[oid] = {}
    else:
        current[attr] = val

print('# Generated by %s' % ' '.join(sys.argv))
print('oids = ', end='')
import pprint
pprint.pprint(oids)
